steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/genial-retina-450108-m4/my-repo/my-image:latest', '.']
images:
- 'us-central1-docker.pkg.dev/genial-retina-450108-m4/my-repo/my-image:latest'
